spring:
  datasource:
    url: jdbc:postgresql://dpg-d7i9l50sfn5c738gl5vg-a.singapore-postgres.render.com:5432/ctk_education?sslmode=require
    username: ctk_education_user
    password: A2L31NAiJ1n93Ldn0j1aZYxZtBBDOfFZ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

server:
  address: 0.0.0.0
  port: 8080


datasource:
  seed:
    enabled: true
